name: Model Training Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run model training
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_PAT }}
          MLFLOW_TRACKING_URI: "https://dagshub.com/lewko98/mlops-quickstart.mlflow"
          MLFLOW_TRACKING_USERNAME: "lewko98"
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python train.py
